config/routes.rb
Rails.application.routes.draw do

  root 'lists#index'

  resources :lists do
    resources :bookmarks, only: [ :new, :create ]
  end

  resources :bookmarks, only: :destroy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  has_one_attached :photo
  validates :photo, presence: true
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  validates :photo, presence: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
 # A movie must have a unique title and an overview.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(strong_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def strong_params
    params.require(:bookmark).permit(:comment, :movie_id, :photo)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

end

#

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
    @list = List.new
    @books = @list.bookmarks
    @bookmarks = Bookmark.where(@books)
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @lists = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Arimo:wght@400;500;700&family=Lobster&family=Monofett&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,500;1,500&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%# <div class="container">
  <div class="container">
    <h1>Your Movie List</h1>
  </div>s
</div> %>

<div class="cont">

  <div class="banner">
    <%= image_tag 'film-reel' %>
    <h1>Movie Night</h1>
  </div>
  <div class="main-body">
    <div class="header">
      <h1>Genres</h1>
    <!-- Modal -->
    <!-- Button trigger modal -->
      <button class="plus" data-bs-toggle="modal" data-bs-target="#exampleModal">
          <i class="fa fa-solid fa-plus"></i>
      </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header" style="background-color: black;">
            <h1 class="modal-title" id="exampleModalLabel" style="font-size: 32px; margin: 0px; color: white; height: 42px;">Add a genre</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" style="background-color: black;">
            <div class="text-start">
              <div class="form-list">
                <%= simple_form_for (@list) do |f| %>
                  <%= f.input :name, placeholder: 'genre' %>
                  <%= f.input :photo, as: :file %>
                  <%= f.submit 'Add', class: 'btn btn-outline-danger btn-sm mt-1' %>
                  <%= link_to 'Cancel', lists_path(@list), class: 'btn btn-outline-danger btn-sm mt-1' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
      <%# <%= link_to 'Add Category', new_list_path, class: 'btn btn-danger' %>




    <!-- cards -->
    <div class="wrapper">
      <% @lists.each do |list| %>
          <div class="films">
        <%= link_to list_path(list) do %>
            <%= cl_image_tag list.photo.key %>
            <div class="card-text">
              <h2 style="color: white; font-family: 'Lobster', cursive; font-size: 38px;"><%= list.name %></h2>
              <h3><%= @bookmarks.count %> movies listed</h3>
              <%= link_to "Delete",
                list_path(list),
                method: :delete,
                data: { confirm: "Are you sure?" }, class: 'btn btn-outline-danger btn-sm mt-1' %>
            </div>
        <% end %>
          </div>
      <% end %>
    </div>
  </div>

</div>


<%# <div class="container p-2">
  <div class="row row-cols-3 ">
      <% @lists.each do |list| %>
          <%# <div class="card d-flex align-items-center justify-content-center">
            <h4><%= link_to list.name, list_path(list) %>
          <%# </div>
      <% end %>
  <%# </div> %>
<%# </div> %>

app/views/lists/new.html.erb
<div class="d-flex align-items-center justify-content-center">
  <div class="text-start">
    <div class="form-list">
      <%= simple_form_for (@list) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
        <%= link_to 'Cancel', lists_path(@list), class: 'btn btn-outline-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="cont">

  <div class="banner">
    <%= link_to root_path do %>
      <%= image_tag 'film-reel' %>
    <% end %>
    <h1>Movie Night</h1>
  </div>
  <div class="main-body">
    <div class="header">
      <h1><%= @list.name %></h1>
      <button class="plus" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <i class="fa fa-solid fa-plus"></i>
      </button>
    </div>
    <div class="bm-wrapper">
      <% @list.bookmarks.each do |bookmark| %>
        <div class="bms">
          <%= cl_image_tag bookmark.photo.key %>
          <div class="bms-text">
            <div class="title-rating">
              <h4 style="font-family: 'Lobster', cursive; font-size: 38px; color: white;"><%= bookmark.movie.title %></h4>
              <div class="rating">
                <h3><%= "#{bookmark.movie.rating}/10" %></h3>
                <%= image_tag "star", style: 'height: 22px; width: 22px; margin-bottom: 6px;'%>
              </div>
            </div>
            <p style="font-weight: 100;"><%= bookmark.movie.overview %></p>
            <p style="color: grey;">"<%= bookmark.comment %>"</p>
            <%= link_to "Delete",
                  bookmark_path(bookmark),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: 'btn btn-outline-danger btn-sm' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
      <!-- Modal -->
      <!-- Button trigger modal -->

      <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="background-color: black;">
          <h1 class="modal-title" id="exampleModalLabel" style="font-size: 32px; margin: 0px; color: white; height: 42px; font-family: 'Lobster'">Add a movie</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" style="background-color: black;">
          <div class="text-start">
            <div class="form-list">
              <%= simple_form_for [@list, @bookmark] do |f| %>
                <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Select a movie", input_html: { data: { controller: "slect2" } } %>
                <%= f.input :comment, placeholder: 'Add your comments' %>
                <%= f.input :photo, as: :file %>
                <%= f.submit 'Add movie', class: 'btn btn-outline-danger btn-sm mb-10px' %>
                <%= link_to 'Cancel', list_path(@list), class: 'btn btn-outline-danger btn-sm' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>